GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "test"
}

###

DELETE http://localhost:3001/todo/delete/620e7c07e7cb1da7a42b8f49

###

PUT http://localhost:3001/todo/complete/620fbb58240adf807cf8a8ab